# Generated by Django 3.0.8 on 2020-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200803_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
