# Generated by Django 3.0.8 on 2020-08-03 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200803_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
